Repository 1project-agora1/P_AGORA, pull requests merged in 2025-02, with the labels that each got.

#8 doc: 2주차 계획
  README.md
Labels: documentation

#15 3주차 계획
  README.md
Labels: documentation

#18 [DOC] 초기 템플릿
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/pull_request-template.md
  .gitignore
Labels: documentation

#24 [FEAT] Prisma 세팅 및 user, post 테이블 생성
  index.js
  package-lock.json
  package.json
  prisma/migrations/20250218074153_1/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
Labels: feat

#27 [FEAT] 해더 스타일 적용 및 공통 폰트, 본문 내용 초기화
  .gitignore
  package.json
  public/fonts/LINESeedKR-Bd.ttf
  public/fonts/LINESeedKR-Rg.ttf
  public/fonts/LINESeedKR-Th.ttf
  public/images/logo.png
  src/app/components/header/Header.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  tailwind.config.ts
Labels: feat

#31 [FEAT] 푸터, 헤더, 사이드바 추가 및 대표 색상
  public/html/privacy.html
  src/app/components/footer/Footer.tsx
  src/app/components/header/Header.tsx
  src/app/components/header/Sidebar.tsx
  src/app/components/sidebar/Sidebar.tsx
  src/app/layout.tsx
  tailwind.config.ts
Labels: documentation, feat

#36 [DOC] 주차별 개발 계획 수정
  README.md
  src/app/favicon.ico
Labels: documentation

#28 [FEAT] 로그인 / 회원가입
  package-lock.json
  package.json
  prisma/migrations/20250221050524_change_password_type/migration.sql
  prisma/schema.prisma
  src/app/api/(auth)/login/route.ts
  src/app/api/(auth)/logout/route.ts
  src/app/api/(auth)/register/route.ts
  src/app/login/page.tsx
  src/app/logout/page.tsx
  src/app/register/page.tsx
  src/components/auth/login-form.tsx
  src/components/auth/logout-form.tsx
  src/components/auth/register-form.tsx
  src/components/loading-spinner.tsx
  src/lib/api-response.ts
  src/lib/cookies.ts
  src/lib/validator.ts
Labels: feat

#39 [FEAT] 로그인 회원 가입 프론트 플로우 수정
  package-lock.json
  package.json
  src/app/components/header/Header.tsx
  src/app/login/page.tsx
  src/components/auth/login-form.tsx
  src/components/auth/login-modal.tsx
Labels: feat

#44 [REFACTOR] cookie 수정 및 불필요한 리턴값 삭제
  package-lock.json
  src/app/api/(auth)/login/route.ts
  src/app/api/(auth)/register/route.ts
  src/lib/cookies.ts
Labels: refactor

#45 [FEAT] package-lock.json 레포 삭제
  package-lock.json
Labels: feat

#53 [REFACTOR] 채널 관련 API 리팩토링
  src/app/api/channel/create/route.ts
  src/app/api/channel/item/create/route.ts
  src/app/api/channel/list/route.ts
  src/lib/query/ChannelQuery.ts
  src/lib/repository/ChannelRepository.ts
  src/lib/request/ChannelRequest.ts
Labels: refactor

#55 [FEAT] SWR 패칭 최적화 및 스켈렌톤 UI 적용
  package.json
  src/components/channel/Channel.tsx
  src/components/header/Header.tsx
Labels: feat

#56 [REFACTOR] 파일 네이밍 및 위치 관련 리팩토링
  eslint.config.mjs
  package.json
  src/app/api/(auth)/login/route.ts
  src/app/api/(auth)/logout/route.ts
  src/app/api/(auth)/register/route.ts
  src/app/api/channel/create/route.ts
  src/app/api/channel/item/create/route.ts
  src/app/api/channel/list/route.ts
  src/app/logout/page.tsx
  src/app/register/page.tsx
  src/components/LoadingSpinner.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/LoginModal.tsx
  src/components/auth/LogoutForm.tsx
  src/components/auth/RegisterForm.tsx
  src/components/channel/Channel.tsx
  src/components/header/Header.tsx
  src/lib/ApiResponse.ts
  src/lib/Cookies.ts
  src/lib/Validator.ts
  src/lib/repository/UserRepository.ts
  src/lib/types/ChannerType.ts
Labels: refactor

#61 [REFACTOR] 오타 수정 및 들여쓰기 적용
  src/components/channel/Channel.tsx
  src/components/footer/Footer.tsx
  src/components/header/Header.tsx
  src/lib/query/ChannelQuery.ts
  src/lib/repository/ChannelRepository.ts
  src/lib/types/ChannerType.ts
  src/util/ConvertBigIntToString.ts
  src/util/RandomToken.ts
Labels: refactor

#68 [REFACTOR] 게시물 미리 보기 API 추가
  prisma/migrations/20250228045424_add_board/migration.sql
  prisma/schema.prisma
  src/app/api/post/list/preview/route.ts
  src/lib/query/PostQuery.ts
  src/lib/repository/PostRepository.ts
Labels: feat

#67 [REFACTOR] 미사용 주석 제거 및 ESLINT 설정 변경
  eslint.config.mjs
  next.config.ts
  src/lib/repository/ChannelRepository.ts
  tailwind.config.ts
Labels: refactor
